### PR TITLE
Setup repository

### PR DESCRIPTION
**Pull request by IamShubhamGupto**
- [x] Add `.gitignore`
- [x] Add `README.md`
- [x] Add `.pre-commit-config.yaml`
- [x] Add `environment.yml`
- [x] Enable branch protection on `main` branch 
- [x] Add `conda-lock`
- [x] Setup Jupyter book
- [x] Setup GitHub pages 
- [x] Setup Github for Jupyter book preview deployment - ReviewNB works well
- [x] Setup Github actions workflow for Jupyter book deployment

### CODE REVIEW

**Comment by IamShubhamGupto** [comment]
Creating the `condo-lock` file for linux using an M1 Mac Pro seems to be taking too long. Its been running overnight and still not finished

**Comment by IamShubhamGupto** [comment]
The fix is to not use the default `conda` environment export, rather manually list the top level dependencies like `pandas` / `xarray`. The remaining is automatically figured out by `condo-lock`

**Comment by IamShubhamGupto** [comment]
Hey @jbusecke in this PR, ive setup basic tools for the repository. I still need to add some GitHub actions I think but I'll reuse the setup from L96. 

Coming to the initial notebooks where we introduce the tools like Xarray and Xgcm, is there a preferred dataset we want to demo this? Currently I can also reuse most of the code from the Pangeo xarray tutorial but that's a bit of duplication. Let me know what you think.

cc @LaureZanna @suryadheeshjith

**Comment by LaureZanna** [comment]
Thanks @IamShubhamGupto and @suryadheeshjith ! I will let @jbusecke check the PR. 

For the dataset: maybe using CM2.6 or some of the OM4 data, might be a good start. @jbusecke @adcroft ?

**Comment by IamShubhamGupto** [comment]
@LaureZanna @jbusecke 
The current PR is ready to go in. The notebook is very minimal right now and probably needs a few more iterations. 
We basically setup all the tools so from the future we only worry about the content displayed in the Jupyter book. 

As for working on CM2.6, is there documentation / paper available online as to what each column contains? 

I found this for OM4 and I think its a good summary and link to the published paper https://www.gfdl.noaa.gov/om4-0/

**Review by LaureZanna — APPROVED** [review]

**Comment by Groundpepper** [comment]
[This](https://github.com/leap-stc/data-management/pull/50) pr identifies all cm2.6 variant datasets on leap. There's no documentation for a deeper level of analysis but you may simply use `xr.open_dataset(store, engine='zarr')` to check variable details for 16 datasets

**Pull request merged**
