### PR TITLE
PR Web Previews

### PR DESCRIPTION
**Pull request by IamShubhamGupto**
- [ ] Closes #xxxx
 - [ ] New notebooks are added to `_toc.yml` and show up properly in website preview.
 - [x] ran pre-commit on the entire repo and should fix the failure

### CODE REVIEW

**Comment by jbusecke** [comment]
Could we add a pre-commit hook which catches these things?

**Comment by IamShubhamGupto** [comment]
@jbusecke with the app enabled it should automatically be able to commit to that branch as a fix (incase the string is missed locally)

**Comment by jbusecke** [comment]
Oh wait I might have misunderstood this PR. It seems like you are experimenting with the preview here?

**Comment by IamShubhamGupto** [comment]
@jbusecke looks like I was wrong, even with app formatting it fails 

I did start this pr for working on the previews but I also wanted to fix the failure. ill figure out how to update hook to fix it in case unformatted commits are made

**Comment by IamShubhamGupto** [comment]
pre-commit.ci autofix

**Comment by IamShubhamGupto** [comment]
@jbusecke 
we need to somehow automatically make the above comment whenever pre-commit checks fail, ive never done this before but your preview example had a yml like https://github.com/leap-stc/leap-stc.github.io/blob/main/.github/workflows/preview-comment.yaml

Ive not done this before so I might take a bit trial and error to figure this as well. If youre sure of what the next step should be, please commit to this branch and let me know, thanks

**Comment by IamShubhamGupto** [comment]
@jbusecke 

the issue was with the order in which pre-commit is run, it will now automatically detect these changes and it will be applied by the bot.

 ill be closing this pr and starting fresh on a new branch.

**Pull request closed without merging**
